version: "3.7"

services:
  web:
    build:
      context: .
      target: ${DOCKER_ENVIRONMENT:-development}
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
    restart: always
